"""Utilities module."""

from .logging import setup_logging, get_logger, logger
from .units import (
    hz_to_khz,
    hz_to_mhz,
    hz_to_ghz,
    format_frequency,
    format_sample_rate,
    format_duration,
    format_data_size,
    db_to_linear,
    linear_to_db,
    amplitude_to_db,
    db_to_amplitude,
    ppm_to_hz,
    hz_to_ppm,
    format_db,
    format_percent,
    get_frequency_axis,
    get_positive_frequency_axis,
)
from .memory import (
    get_available_memory_mb,
    get_total_memory_mb,
    get_memory_usage_mb,
    estimate_array_memory,
    check_memory_requirement,
    get_optimal_chunk_size,
    MemoryMonitor,
)
from .performance import (
    Timer,
    PerformanceMonitor,
    TimingResult,
    get_performance_monitor,
    timed,
)

__all__ = [
    "setup_logging",
    "get_logger",
    "logger",
    "hz_to_khz",
    "hz_to_mhz",
    "hz_to_ghz",
    "format_frequency",
    "format_sample_rate",
    "format_duration",
    "format_data_size",
    "db_to_linear",
    "linear_to_db",
    "amplitude_to_db",
    "db_to_amplitude",
    "ppm_to_hz",
    "hz_to_ppm",
    "format_db",
    "format_percent",
    "get_frequency_axis",
    "get_positive_frequency_axis",
    "get_available_memory_mb",
    "get_total_memory_mb",
    "get_memory_usage_mb",
    "estimate_array_memory",
    "check_memory_requirement",
    "get_optimal_chunk_size",
    "MemoryMonitor",
    "Timer",
    "PerformanceMonitor",
    "TimingResult",
    "get_performance_monitor",
    "timed",
]